// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_USER         Role = 0
	Role_TENANT_ADMIN Role = 1
	Role_ADMIN        Role = 2
)

var Role_name = map[int32]string{
	0: "USER",
	1: "TENANT_ADMIN",
	2: "ADMIN",
}

var Role_value = map[string]int32{
	"USER":         0,
	"TENANT_ADMIN": 1,
	"ADMIN":        2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type NotificationType int32

const (
	NotificationType_NONE  NotificationType = 0
	NotificationType_SMS   NotificationType = 1
	NotificationType_CALL  NotificationType = 2
	NotificationType_EMAIL NotificationType = 3
)

var NotificationType_name = map[int32]string{
	0: "NONE",
	1: "SMS",
	2: "CALL",
	3: "EMAIL",
}

var NotificationType_value = map[string]int32{
	"NONE":  0,
	"SMS":   1,
	"CALL":  2,
	"EMAIL": 3,
}

func (x NotificationType) String() string {
	return proto.EnumName(NotificationType_name, int32(x))
}

func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type UserNotificationStatus int32

const (
	UserNotificationStatus_PENDING UserNotificationStatus = 0
	UserNotificationStatus_SENT    UserNotificationStatus = 1
	UserNotificationStatus_FAILED  UserNotificationStatus = 2
)

var UserNotificationStatus_name = map[int32]string{
	0: "PENDING",
	1: "SENT",
	2: "FAILED",
}

var UserNotificationStatus_value = map[string]int32{
	"PENDING": 0,
	"SENT":    1,
	"FAILED":  2,
}

func (x UserNotificationStatus) String() string {
	return proto.EnumName(UserNotificationStatus_name, int32(x))
}

func (UserNotificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

type NotificationSettings struct {
	Type                 NotificationType `protobuf:"varint,1,opt,name=type,proto3,enum=v1.NotificationType" json:"type,omitempty"`
	Priority             int32            `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NotificationSettings) Reset()         { *m = NotificationSettings{} }
func (m *NotificationSettings) String() string { return proto.CompactTextString(m) }
func (*NotificationSettings) ProtoMessage()    {}
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *NotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationSettings.Unmarshal(m, b)
}
func (m *NotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationSettings.Marshal(b, m, deterministic)
}
func (m *NotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationSettings.Merge(m, src)
}
func (m *NotificationSettings) XXX_Size() int {
	return xxx_messageInfo_NotificationSettings.Size(m)
}
func (m *NotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationSettings proto.InternalMessageInfo

func (m *NotificationSettings) GetType() NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationType_NONE
}

func (m *NotificationSettings) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type UserNotification struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AlertId              int64                  `protobuf:"varint,5,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	ShortMessage         string                 `protobuf:"bytes,6,opt,name=short_message,json=shortMessage,proto3" json:"short_message,omitempty"`
	LongMessage          string                 `protobuf:"bytes,7,opt,name=long_message,json=longMessage,proto3" json:"long_message,omitempty"`
	Type                 NotificationType       `protobuf:"varint,8,opt,name=type,proto3,enum=v1.NotificationType" json:"type,omitempty"`
	CreatedAt            *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt               *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	TenantName           string                 `protobuf:"bytes,11,opt,name=tenantName,proto3" json:"tenantName,omitempty"`
	TenantCode           string                 `protobuf:"bytes,12,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	RefId                string                 `protobuf:"bytes,13,opt,name=refId,proto3" json:"refId,omitempty"`
	Status               UserNotificationStatus `protobuf:"varint,14,opt,name=status,proto3,enum=v1.UserNotificationStatus" json:"status,omitempty"`
	Reason               string                 `protobuf:"bytes,16,opt,name=reason,proto3" json:"reason,omitempty"`
	Price                float32                `protobuf:"fixed32,17,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserNotification) Reset()         { *m = UserNotification{} }
func (m *UserNotification) String() string { return proto.CompactTextString(m) }
func (*UserNotification) ProtoMessage()    {}
func (*UserNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotification.Unmarshal(m, b)
}
func (m *UserNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotification.Marshal(b, m, deterministic)
}
func (m *UserNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotification.Merge(m, src)
}
func (m *UserNotification) XXX_Size() int {
	return xxx_messageInfo_UserNotification.Size(m)
}
func (m *UserNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotification.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotification proto.InternalMessageInfo

func (m *UserNotification) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserNotification) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserNotification) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserNotification) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserNotification) GetAlertId() int64 {
	if m != nil {
		return m.AlertId
	}
	return 0
}

func (m *UserNotification) GetShortMessage() string {
	if m != nil {
		return m.ShortMessage
	}
	return ""
}

func (m *UserNotification) GetLongMessage() string {
	if m != nil {
		return m.LongMessage
	}
	return ""
}

func (m *UserNotification) GetType() NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationType_NONE
}

func (m *UserNotification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserNotification) GetSentAt() *timestamp.Timestamp {
	if m != nil {
		return m.SentAt
	}
	return nil
}

func (m *UserNotification) GetTenantName() string {
	if m != nil {
		return m.TenantName
	}
	return ""
}

func (m *UserNotification) GetTenantCode() string {
	if m != nil {
		return m.TenantCode
	}
	return ""
}

func (m *UserNotification) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *UserNotification) GetStatus() UserNotificationStatus {
	if m != nil {
		return m.Status
	}
	return UserNotificationStatus_PENDING
}

func (m *UserNotification) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *UserNotification) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type UserNotificationUpdateRequest struct {
	RefId                string                 `protobuf:"bytes,1,opt,name=refId,proto3" json:"refId,omitempty"`
	Status               UserNotificationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=v1.UserNotificationStatus" json:"status,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Id                   int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	SentAt               *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Price                float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserNotificationUpdateRequest) Reset()         { *m = UserNotificationUpdateRequest{} }
func (m *UserNotificationUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UserNotificationUpdateRequest) ProtoMessage()    {}
func (*UserNotificationUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserNotificationUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotificationUpdateRequest.Unmarshal(m, b)
}
func (m *UserNotificationUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotificationUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UserNotificationUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotificationUpdateRequest.Merge(m, src)
}
func (m *UserNotificationUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UserNotificationUpdateRequest.Size(m)
}
func (m *UserNotificationUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotificationUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotificationUpdateRequest proto.InternalMessageInfo

func (m *UserNotificationUpdateRequest) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *UserNotificationUpdateRequest) GetStatus() UserNotificationStatus {
	if m != nil {
		return m.Status
	}
	return UserNotificationStatus_PENDING
}

func (m *UserNotificationUpdateRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *UserNotificationUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserNotificationUpdateRequest) GetSentAt() *timestamp.Timestamp {
	if m != nil {
		return m.SentAt
	}
	return nil
}

func (m *UserNotificationUpdateRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type User struct {
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string                  `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string                  `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                  `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	TenantId             int64                   `protobuf:"varint,6,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Role                 Role                    `protobuf:"varint,7,opt,name=role,proto3,enum=v1.Role" json:"role,omitempty"`
	Mobile               string                  `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Notifications        []*NotificationSettings `protobuf:"bytes,9,rep,name=notifications,proto3" json:"notifications,omitempty"`
	CreatedAt            *timestamp.Timestamp    `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp    `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PasswordResetToken   string                  `protobuf:"bytes,12,opt,name=passwordResetToken,proto3" json:"passwordResetToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *User) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetNotifications() []*NotificationSettings {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

type CreateUserRequest struct {
	FirstName            string                  `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string                  `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string                  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                  `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Telephone            string                  `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Mobile               string                  `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	TenantId             int64                   `protobuf:"varint,7,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Role                 Role                    `protobuf:"varint,8,opt,name=role,proto3,enum=v1.Role" json:"role,omitempty"`
	Notifications        []*NotificationSettings `protobuf:"bytes,9,rep,name=notifications,proto3" json:"notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *CreateUserRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CreateUserRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *CreateUserRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

func (m *CreateUserRequest) GetNotifications() []*NotificationSettings {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type CreateUserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateUserRequest struct {
	User                 *User                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId             int64    `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role                 Role     `protobuf:"varint,3,opt,name=role,proto3,enum=v1.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *GetUserRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

type GetUserResponse struct {
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string                  `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string                  `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	TenantId             int64                   `protobuf:"varint,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Tenant               *Tenant                 `protobuf:"bytes,6,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Role                 Role                    `protobuf:"varint,7,opt,name=role,proto3,enum=v1.Role" json:"role,omitempty"`
	Mobile               string                  `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Notifications        []*NotificationSettings `protobuf:"bytes,9,rep,name=notifications,proto3" json:"notifications,omitempty"`
	CreatedAt            *timestamp.Timestamp    `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp    `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PasswordResetToken   string                  `protobuf:"bytes,12,opt,name=passwordResetToken,proto3" json:"passwordResetToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *GetUserResponse) GetTenant() *Tenant {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *GetUserResponse) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

func (m *GetUserResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetUserResponse) GetNotifications() []*NotificationSettings {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *GetUserResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetUserResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *GetUserResponse) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

type ListUsersRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	TenantId             int64    `protobuf:"varint,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role                 Role     `protobuf:"varint,5,opt,name=role,proto3,enum=v1.Role" json:"role,omitempty"`
	Limit                int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ListUsersRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ListUsersRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ListUsersRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *ListUsersRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

func (m *ListUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListUserNotificationsRequest struct {
	UserId               int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AlertId              int64                  `protobuf:"varint,4,opt,name=alertId,proto3" json:"alertId,omitempty"`
	CreatedAtStart       *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=createdAtStart,proto3" json:"createdAtStart,omitempty"`
	CreatedAtEnd         *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=createdAtEnd,proto3" json:"createdAtEnd,omitempty"`
	SentAtStart          *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=sentAtStart,proto3" json:"sentAtStart,omitempty"`
	SentAtEnd            *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=sentAtEnd,proto3" json:"sentAtEnd,omitempty"`
	Status               UserNotificationStatus `protobuf:"varint,9,opt,name=status,proto3,enum=v1.UserNotificationStatus" json:"status,omitempty"`
	Type                 NotificationType       `protobuf:"varint,10,opt,name=type,proto3,enum=v1.NotificationType" json:"type,omitempty"`
	Limit                int32                  `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                  `protobuf:"varint,12,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListUserNotificationsRequest) Reset()         { *m = ListUserNotificationsRequest{} }
func (m *ListUserNotificationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserNotificationsRequest) ProtoMessage()    {}
func (*ListUserNotificationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *ListUserNotificationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserNotificationsRequest.Unmarshal(m, b)
}
func (m *ListUserNotificationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserNotificationsRequest.Marshal(b, m, deterministic)
}
func (m *ListUserNotificationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserNotificationsRequest.Merge(m, src)
}
func (m *ListUserNotificationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserNotificationsRequest.Size(m)
}
func (m *ListUserNotificationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserNotificationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserNotificationsRequest proto.InternalMessageInfo

func (m *ListUserNotificationsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListUserNotificationsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ListUserNotificationsRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ListUserNotificationsRequest) GetAlertId() int64 {
	if m != nil {
		return m.AlertId
	}
	return 0
}

func (m *ListUserNotificationsRequest) GetCreatedAtStart() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtStart
	}
	return nil
}

func (m *ListUserNotificationsRequest) GetCreatedAtEnd() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtEnd
	}
	return nil
}

func (m *ListUserNotificationsRequest) GetSentAtStart() *timestamp.Timestamp {
	if m != nil {
		return m.SentAtStart
	}
	return nil
}

func (m *ListUserNotificationsRequest) GetSentAtEnd() *timestamp.Timestamp {
	if m != nil {
		return m.SentAtEnd
	}
	return nil
}

func (m *ListUserNotificationsRequest) GetStatus() UserNotificationStatus {
	if m != nil {
		return m.Status
	}
	return UserNotificationStatus_PENDING
}

func (m *ListUserNotificationsRequest) GetType() NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationType_NONE
}

func (m *ListUserNotificationsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUserNotificationsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListUserNotificationsResponse struct {
	Notifications        []*UserNotification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total                int32               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListUserNotificationsResponse) Reset()         { *m = ListUserNotificationsResponse{} }
func (m *ListUserNotificationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserNotificationsResponse) ProtoMessage()    {}
func (*ListUserNotificationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *ListUserNotificationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserNotificationsResponse.Unmarshal(m, b)
}
func (m *ListUserNotificationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserNotificationsResponse.Marshal(b, m, deterministic)
}
func (m *ListUserNotificationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserNotificationsResponse.Merge(m, src)
}
func (m *ListUserNotificationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserNotificationsResponse.Size(m)
}
func (m *ListUserNotificationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserNotificationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserNotificationsResponse proto.InternalMessageInfo

func (m *ListUserNotificationsResponse) GetNotifications() []*UserNotification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *ListUserNotificationsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetUserByEmailAndPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantId             int64    `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailAndPasswordRequest) Reset()         { *m = GetUserByEmailAndPasswordRequest{} }
func (m *GetUserByEmailAndPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailAndPasswordRequest) ProtoMessage()    {}
func (*GetUserByEmailAndPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *GetUserByEmailAndPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailAndPasswordRequest.Unmarshal(m, b)
}
func (m *GetUserByEmailAndPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailAndPasswordRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailAndPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailAndPasswordRequest.Merge(m, src)
}
func (m *GetUserByEmailAndPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailAndPasswordRequest.Size(m)
}
func (m *GetUserByEmailAndPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailAndPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailAndPasswordRequest proto.InternalMessageInfo

func (m *GetUserByEmailAndPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByEmailAndPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetUserByEmailAndPasswordRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

type ResetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPasswordResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

func (m *ResetPasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdatePasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{17}
}

func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(m, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

type NotificationsReport struct {
	Sent                 int32    `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Failed               int32    `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Pending              int32    `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Cost                 float32  `protobuf:"fixed32,4,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationsReport) Reset()         { *m = NotificationsReport{} }
func (m *NotificationsReport) String() string { return proto.CompactTextString(m) }
func (*NotificationsReport) ProtoMessage()    {}
func (*NotificationsReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{18}
}

func (m *NotificationsReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationsReport.Unmarshal(m, b)
}
func (m *NotificationsReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationsReport.Marshal(b, m, deterministic)
}
func (m *NotificationsReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationsReport.Merge(m, src)
}
func (m *NotificationsReport) XXX_Size() int {
	return xxx_messageInfo_NotificationsReport.Size(m)
}
func (m *NotificationsReport) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationsReport.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationsReport proto.InternalMessageInfo

func (m *NotificationsReport) GetSent() int32 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *NotificationsReport) GetFailed() int32 {
	if m != nil {
		return m.Failed
	}
	return 0
}

func (m *NotificationsReport) GetPending() int32 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *NotificationsReport) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type Report struct {
	Total                int32                           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Cost                 float32                         `protobuf:"fixed32,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Data                 map[string]*NotificationsReport `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{19}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Report) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Report) GetData() map[string]*NotificationsReport {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetReportRequest struct {
	TenantId             int64    `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReportRequest) Reset()         { *m = GetReportRequest{} }
func (m *GetReportRequest) String() string { return proto.CompactTextString(m) }
func (*GetReportRequest) ProtoMessage()    {}
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{20}
}

func (m *GetReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReportRequest.Unmarshal(m, b)
}
func (m *GetReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReportRequest.Marshal(b, m, deterministic)
}
func (m *GetReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReportRequest.Merge(m, src)
}
func (m *GetReportRequest) XXX_Size() int {
	return xxx_messageInfo_GetReportRequest.Size(m)
}
func (m *GetReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReportRequest proto.InternalMessageInfo

func (m *GetReportRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

type Tenant struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string               `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Credit               float32              `protobuf:"fixed32,5,opt,name=credit,proto3" json:"credit,omitempty"`
	LogoUrl              string               `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Tenant) Reset()         { *m = Tenant{} }
func (m *Tenant) String() string { return proto.CompactTextString(m) }
func (*Tenant) ProtoMessage()    {}
func (*Tenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{21}
}

func (m *Tenant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tenant.Unmarshal(m, b)
}
func (m *Tenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tenant.Marshal(b, m, deterministic)
}
func (m *Tenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tenant.Merge(m, src)
}
func (m *Tenant) XXX_Size() int {
	return xxx_messageInfo_Tenant.Size(m)
}
func (m *Tenant) XXX_DiscardUnknown() {
	xxx_messageInfo_Tenant.DiscardUnknown(m)
}

var xxx_messageInfo_Tenant proto.InternalMessageInfo

func (m *Tenant) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tenant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tenant) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Tenant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Tenant) GetCredit() float32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *Tenant) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *Tenant) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Tenant) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateTenantRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	LogoUrl              string   `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTenantRequest) Reset()         { *m = CreateTenantRequest{} }
func (m *CreateTenantRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTenantRequest) ProtoMessage()    {}
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{22}
}

func (m *CreateTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTenantRequest.Unmarshal(m, b)
}
func (m *CreateTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTenantRequest.Marshal(b, m, deterministic)
}
func (m *CreateTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTenantRequest.Merge(m, src)
}
func (m *CreateTenantRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTenantRequest.Size(m)
}
func (m *CreateTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTenantRequest proto.InternalMessageInfo

func (m *CreateTenantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTenantRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateTenantRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateTenantRequest) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type UpdateTenantRequest struct {
	Tenant               *Tenant               `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateTenantRequest) Reset()         { *m = UpdateTenantRequest{} }
func (m *UpdateTenantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTenantRequest) ProtoMessage()    {}
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{23}
}

func (m *UpdateTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTenantRequest.Unmarshal(m, b)
}
func (m *UpdateTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTenantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTenantRequest.Merge(m, src)
}
func (m *UpdateTenantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTenantRequest.Size(m)
}
func (m *UpdateTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTenantRequest proto.InternalMessageInfo

func (m *UpdateTenantRequest) GetTenant() *Tenant {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *UpdateTenantRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetTenantRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTenantRequest) Reset()         { *m = GetTenantRequest{} }
func (m *GetTenantRequest) String() string { return proto.CompactTextString(m) }
func (*GetTenantRequest) ProtoMessage()    {}
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{24}
}

func (m *GetTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTenantRequest.Unmarshal(m, b)
}
func (m *GetTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTenantRequest.Marshal(b, m, deterministic)
}
func (m *GetTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantRequest.Merge(m, src)
}
func (m *GetTenantRequest) XXX_Size() int {
	return xxx_messageInfo_GetTenantRequest.Size(m)
}
func (m *GetTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantRequest proto.InternalMessageInfo

func (m *GetTenantRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListTenantsRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=v1.Role" json:"role,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTenantsRequest) Reset()         { *m = ListTenantsRequest{} }
func (m *ListTenantsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTenantsRequest) ProtoMessage()    {}
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{25}
}

func (m *ListTenantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTenantsRequest.Unmarshal(m, b)
}
func (m *ListTenantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTenantsRequest.Marshal(b, m, deterministic)
}
func (m *ListTenantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTenantsRequest.Merge(m, src)
}
func (m *ListTenantsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTenantsRequest.Size(m)
}
func (m *ListTenantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTenantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTenantsRequest proto.InternalMessageInfo

func (m *ListTenantsRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListTenantsRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

func (m *ListTenantsRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListTenantsResponse struct {
	Tenants              []*Tenant `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListTenantsResponse) Reset()         { *m = ListTenantsResponse{} }
func (m *ListTenantsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTenantsResponse) ProtoMessage()    {}
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{26}
}

func (m *ListTenantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTenantsResponse.Unmarshal(m, b)
}
func (m *ListTenantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTenantsResponse.Marshal(b, m, deterministic)
}
func (m *ListTenantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTenantsResponse.Merge(m, src)
}
func (m *ListTenantsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTenantsResponse.Size(m)
}
func (m *ListTenantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTenantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTenantsResponse proto.InternalMessageInfo

func (m *ListTenantsResponse) GetTenants() []*Tenant {
	if m != nil {
		return m.Tenants
	}
	return nil
}

type Payment struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId             int64                `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Ref                  string               `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Amount               float32              `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentDate          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	PaidBy               int64                `protobuf:"varint,6,opt,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            int64                `protobuf:"varint,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{27}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payment) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *Payment) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *Payment) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetPaymentDate() *timestamp.Timestamp {
	if m != nil {
		return m.PaymentDate
	}
	return nil
}

func (m *Payment) GetPaidBy() int64 {
	if m != nil {
		return m.PaidBy
	}
	return 0
}

func (m *Payment) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Payment) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

type GetPaymentRequest struct {
	TenantId             int64    `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PaymentId            int64    `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentRequest) Reset()         { *m = GetPaymentRequest{} }
func (m *GetPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*GetPaymentRequest) ProtoMessage()    {}
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{28}
}

func (m *GetPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentRequest.Unmarshal(m, b)
}
func (m *GetPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentRequest.Marshal(b, m, deterministic)
}
func (m *GetPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentRequest.Merge(m, src)
}
func (m *GetPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_GetPaymentRequest.Size(m)
}
func (m *GetPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentRequest proto.InternalMessageInfo

func (m *GetPaymentRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *GetPaymentRequest) GetPaymentId() int64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

type CreatePaymentRequest struct {
	TenantId             int64                `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Ref                  string               `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Amount               float32              `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentDate          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	PaidBy               int64                `protobuf:"varint,5,opt,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatePaymentRequest) Reset()         { *m = CreatePaymentRequest{} }
func (m *CreatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentRequest) ProtoMessage()    {}
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{29}
}

func (m *CreatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentRequest.Unmarshal(m, b)
}
func (m *CreatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentRequest.Merge(m, src)
}
func (m *CreatePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentRequest.Size(m)
}
func (m *CreatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentRequest proto.InternalMessageInfo

func (m *CreatePaymentRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *CreatePaymentRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *CreatePaymentRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreatePaymentRequest) GetPaymentDate() *timestamp.Timestamp {
	if m != nil {
		return m.PaymentDate
	}
	return nil
}

func (m *CreatePaymentRequest) GetPaidBy() int64 {
	if m != nil {
		return m.PaidBy
	}
	return 0
}

type ListPaymentsRequest struct {
	TenantId             int64    `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPaymentsRequest) Reset()         { *m = ListPaymentsRequest{} }
func (m *ListPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPaymentsRequest) ProtoMessage()    {}
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{30}
}

func (m *ListPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentsRequest.Unmarshal(m, b)
}
func (m *ListPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentsRequest.Marshal(b, m, deterministic)
}
func (m *ListPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentsRequest.Merge(m, src)
}
func (m *ListPaymentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPaymentsRequest.Size(m)
}
func (m *ListPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentsRequest proto.InternalMessageInfo

func (m *ListPaymentsRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

type ListPaymentsResponse struct {
	Payments             []*Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListPaymentsResponse) Reset()         { *m = ListPaymentsResponse{} }
func (m *ListPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPaymentsResponse) ProtoMessage()    {}
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{31}
}

func (m *ListPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentsResponse.Unmarshal(m, b)
}
func (m *ListPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentsResponse.Marshal(b, m, deterministic)
}
func (m *ListPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentsResponse.Merge(m, src)
}
func (m *ListPaymentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPaymentsResponse.Size(m)
}
func (m *ListPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentsResponse proto.InternalMessageInfo

func (m *ListPaymentsResponse) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func init() {
	proto.RegisterEnum("v1.Role", Role_name, Role_value)
	proto.RegisterEnum("v1.NotificationType", NotificationType_name, NotificationType_value)
	proto.RegisterEnum("v1.UserNotificationStatus", UserNotificationStatus_name, UserNotificationStatus_value)
	proto.RegisterType((*NotificationSettings)(nil), "v1.NotificationSettings")
	proto.RegisterType((*UserNotification)(nil), "v1.UserNotification")
	proto.RegisterType((*UserNotificationUpdateRequest)(nil), "v1.UserNotificationUpdateRequest")
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*CreateUserRequest)(nil), "v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "v1.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "v1.UpdateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "v1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "v1.GetUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "v1.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "v1.ListUsersResponse")
	proto.RegisterType((*ListUserNotificationsRequest)(nil), "v1.ListUserNotificationsRequest")
	proto.RegisterType((*ListUserNotificationsResponse)(nil), "v1.ListUserNotificationsResponse")
	proto.RegisterType((*GetUserByEmailAndPasswordRequest)(nil), "v1.GetUserByEmailAndPasswordRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "v1.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "v1.ResetPasswordResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "v1.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "v1.UpdatePasswordResponse")
	proto.RegisterType((*NotificationsReport)(nil), "v1.NotificationsReport")
	proto.RegisterType((*Report)(nil), "v1.Report")
	proto.RegisterMapType((map[string]*NotificationsReport)(nil), "v1.Report.DataEntry")
	proto.RegisterType((*GetReportRequest)(nil), "v1.GetReportRequest")
	proto.RegisterType((*Tenant)(nil), "v1.Tenant")
	proto.RegisterType((*CreateTenantRequest)(nil), "v1.CreateTenantRequest")
	proto.RegisterType((*UpdateTenantRequest)(nil), "v1.UpdateTenantRequest")
	proto.RegisterType((*GetTenantRequest)(nil), "v1.GetTenantRequest")
	proto.RegisterType((*ListTenantsRequest)(nil), "v1.ListTenantsRequest")
	proto.RegisterType((*ListTenantsResponse)(nil), "v1.ListTenantsResponse")
	proto.RegisterType((*Payment)(nil), "v1.Payment")
	proto.RegisterType((*GetPaymentRequest)(nil), "v1.GetPaymentRequest")
	proto.RegisterType((*CreatePaymentRequest)(nil), "v1.CreatePaymentRequest")
	proto.RegisterType((*ListPaymentsRequest)(nil), "v1.ListPaymentsRequest")
	proto.RegisterType((*ListPaymentsResponse)(nil), "v1.ListPaymentsResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 1663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0xff, 0xf4, 0x33, 0x72, 0x5c, 0x7a, 0xad, 0x38, 0xac, 0x63, 0xa7, 0x2a, 0x1b, 0xa0,
	0x46, 0xd0, 0x28, 0x88, 0xf3, 0x92, 0x9f, 0x36, 0x85, 0x1c, 0x2b, 0x86, 0x00, 0x5b, 0x31, 0x68,
	0xbb, 0x2f, 0x2d, 0x20, 0xac, 0xcd, 0x95, 0x43, 0x98, 0x22, 0x15, 0x72, 0x95, 0x42, 0x17, 0xe8,
	0x01, 0x7a, 0x80, 0x1e, 0xa1, 0x7d, 0xe9, 0x43, 0x0f, 0xd1, 0xde, 0xa0, 0x77, 0x69, 0xb1, 0x3f,
	0xa4, 0x48, 0x9a, 0xb2, 0x95, 0xa4, 0x8f, 0x7d, 0xe3, 0xcc, 0xce, 0xee, 0xce, 0xcc, 0xf7, 0xcd,
	0xce, 0x10, 0x60, 0x12, 0x93, 0xa8, 0x3d, 0x8e, 0x42, 0x1a, 0x22, 0xf5, 0xdd, 0xa3, 0xf5, 0x8d,
	0xf3, 0x30, 0x3c, 0xf7, 0xc9, 0x43, 0x3c, 0xf6, 0x1e, 0xe2, 0x20, 0x08, 0x29, 0xa6, 0x5e, 0x18,
	0xc4, 0xc2, 0x62, 0xfd, 0x33, 0xb9, 0xca, 0xa5, 0xd3, 0xc9, 0xf0, 0x21, 0xf5, 0x46, 0x24, 0xa6,
	0x78, 0x34, 0x96, 0x06, 0xad, 0xa2, 0xc1, 0xd0, 0x23, 0xbe, 0x3b, 0x18, 0xe1, 0xf8, 0x42, 0x58,
	0xd8, 0x3f, 0x40, 0xb3, 0x1f, 0x52, 0x6f, 0xe8, 0x9d, 0xf1, 0x93, 0x8f, 0x08, 0xa5, 0x5e, 0x70,
	0x1e, 0xa3, 0x2d, 0xd0, 0xe9, 0x74, 0x4c, 0x2c, 0xa5, 0xa5, 0x6c, 0x2d, 0x6f, 0x37, 0xdb, 0xef,
	0x1e, 0xb5, 0xb3, 0x76, 0xc7, 0xd3, 0x31, 0x71, 0xb8, 0x05, 0x5a, 0x87, 0xda, 0x38, 0xf2, 0xc2,
	0xc8, 0xa3, 0x53, 0x4b, 0x6d, 0x29, 0x5b, 0x86, 0x93, 0xca, 0xf6, 0x2f, 0x3a, 0x98, 0x27, 0x31,
	0x89, 0xb2, 0x5b, 0xd1, 0x32, 0xa8, 0x9e, 0xcb, 0x0f, 0xd6, 0x1c, 0xd5, 0x73, 0xd1, 0x6d, 0xa8,
	0xb2, 0xa8, 0x07, 0x9e, 0xcb, 0xf7, 0x6b, 0x4e, 0x85, 0x89, 0x3d, 0x17, 0x35, 0xc1, 0x20, 0x23,
	0xec, 0xf9, 0x96, 0xd6, 0x52, 0xb6, 0xea, 0x8e, 0x10, 0xd0, 0x1a, 0x54, 0x46, 0xe1, 0xa9, 0xe7,
	0x13, 0x4b, 0xe7, 0x6a, 0x29, 0xa1, 0x4f, 0xa1, 0x86, 0x7d, 0x12, 0x51, 0x76, 0x8e, 0xc1, 0xcf,
	0xa9, 0x72, 0xb9, 0xe7, 0xa2, 0x2f, 0xe0, 0x66, 0xfc, 0x26, 0x8c, 0xe8, 0x60, 0x44, 0xe2, 0x18,
	0x9f, 0x13, 0xab, 0xc2, 0x77, 0x2e, 0x71, 0xe5, 0x81, 0xd0, 0xa1, 0xcf, 0x61, 0xc9, 0x0f, 0x83,
	0xf3, 0xd4, 0xa6, 0xca, 0x6d, 0x1a, 0x4c, 0x97, 0x98, 0x24, 0x49, 0xa9, 0x5d, 0x9b, 0x94, 0xa7,
	0x00, 0x67, 0x11, 0xc1, 0x94, 0xb8, 0x03, 0x4c, 0xad, 0x7a, 0x4b, 0xd9, 0x6a, 0x6c, 0xaf, 0xb7,
	0x05, 0x1a, 0xed, 0x04, 0x8d, 0xf6, 0x71, 0x02, 0x97, 0x53, 0x97, 0xd6, 0x1d, 0x8a, 0x1e, 0x43,
	0x35, 0x26, 0x01, 0x65, 0xfb, 0xe0, 0xda, 0x7d, 0x15, 0x66, 0xda, 0xa1, 0xe8, 0x2e, 0x00, 0x25,
	0x01, 0x0e, 0x68, 0x1f, 0x8f, 0x88, 0xd5, 0xe0, 0xae, 0x67, 0x34, 0xb3, 0xf5, 0x97, 0xa1, 0x4b,
	0xac, 0xa5, 0xec, 0x3a, 0xd3, 0xb0, 0x54, 0x47, 0x64, 0xd8, 0x73, 0xad, 0x9b, 0x22, 0xd5, 0x5c,
	0x40, 0xdb, 0x50, 0x89, 0x29, 0xa6, 0x93, 0xd8, 0x5a, 0xe6, 0x11, 0xaf, 0xb3, 0x88, 0x8b, 0x78,
	0x1e, 0x71, 0x0b, 0x47, 0x5a, 0x32, 0x78, 0x22, 0x82, 0xe3, 0x30, 0xb0, 0x4c, 0x01, 0x8f, 0x90,
	0xd8, 0x0d, 0xe3, 0xc8, 0x3b, 0x23, 0xd6, 0x4a, 0x4b, 0xd9, 0x52, 0x1d, 0x21, 0xd8, 0x7f, 0x2b,
	0xb0, 0x59, 0x3c, 0xf0, 0x64, 0xec, 0x62, 0x4a, 0x1c, 0xf2, 0x76, 0x42, 0x62, 0x3a, 0xf3, 0x4c,
	0x29, 0xf7, 0x4c, 0xfd, 0x00, 0xcf, 0xb4, 0x9c, 0x67, 0x82, 0x8f, 0x7a, 0xca, 0xc7, 0x0c, 0x00,
	0xc6, 0xc2, 0x00, 0xa4, 0xe1, 0x55, 0xb2, 0xe1, 0xfd, 0xa1, 0x81, 0xce, 0xbc, 0xba, 0xc4, 0xf9,
	0x0d, 0xa8, 0x0f, 0xbd, 0x28, 0x16, 0x70, 0xa9, 0xdc, 0x9d, 0x99, 0x82, 0x95, 0x94, 0x8f, 0xe5,
	0xa2, 0xf0, 0x35, 0x95, 0x67, 0x45, 0xa1, 0x67, 0x8b, 0x82, 0x15, 0x21, 0x8e, 0xe3, 0x1f, 0xc3,
	0x48, 0x90, 0xbf, 0xee, 0xa4, 0x32, 0x5b, 0x13, 0x48, 0xf7, 0x5c, 0xee, 0x9d, 0xe6, 0xa4, 0x32,
	0xda, 0x00, 0x3d, 0x0a, 0x7d, 0x41, 0xf6, 0xe5, 0xed, 0x1a, 0xcb, 0xa2, 0x13, 0xfa, 0xc4, 0xe1,
	0xda, 0x4c, 0xa9, 0xd5, 0x72, 0xa5, 0xf6, 0x02, 0x6e, 0x06, 0x99, 0x3c, 0xc7, 0x56, 0xbd, 0xa5,
	0x6d, 0x35, 0xb6, 0xad, 0x62, 0x41, 0x24, 0xaf, 0x89, 0x93, 0x37, 0x47, 0x4f, 0x60, 0xc6, 0xf7,
	0x05, 0x48, 0x9e, 0x29, 0x8e, 0x27, 0x50, 0x9f, 0x70, 0x7a, 0xb0, 0x9d, 0x8d, 0xeb, 0x77, 0xa6,
	0xc6, 0xa8, 0x0d, 0x28, 0xc9, 0x88, 0x43, 0x62, 0x42, 0x8f, 0xc3, 0x0b, 0x12, 0xc8, 0x4a, 0x28,
	0x59, 0xb1, 0x7f, 0x53, 0x61, 0xe5, 0x25, 0xbf, 0x97, 0x01, 0x98, 0xb0, 0x31, 0x87, 0x9b, 0x72,
	0x15, 0x6e, 0xea, 0x3c, 0xdc, 0xb4, 0x79, 0xb8, 0xe9, 0x05, 0xdc, 0x36, 0xa0, 0x4e, 0x89, 0x4f,
	0xc6, 0x6f, 0xc2, 0x80, 0x48, 0x50, 0x67, 0x8a, 0x0c, 0x36, 0x95, 0x1c, 0x36, 0x59, 0xb4, 0xab,
	0x73, 0xd0, 0xae, 0x95, 0xa2, 0xfd, 0x91, 0xa8, 0xda, 0xf7, 0x00, 0x65, 0x13, 0x16, 0x8f, 0xc3,
	0x20, 0x26, 0x45, 0xe6, 0xdb, 0x04, 0x56, 0x44, 0x81, 0xe7, 0xd3, 0xaa, 0xb3, 0x37, 0x9f, 0x9b,
	0x35, 0x84, 0x63, 0x7c, 0x99, 0x6b, 0x59, 0xb1, 0xf3, 0xbe, 0x25, 0x8a, 0xbd, 0x0c, 0xf1, 0x57,
	0x6c, 0xf9, 0x00, 0xc7, 0x17, 0x8e, 0xb4, 0xb4, 0xbf, 0x87, 0xe5, 0x3d, 0x42, 0xb3, 0x77, 0x14,
	0x4b, 0xf0, 0x0e, 0x4b, 0x2f, 0x4b, 0xcc, 0xac, 0xf1, 0x5c, 0xce, 0x94, 0x56, 0x96, 0x29, 0xfb,
	0x4f, 0x0d, 0x3e, 0x49, 0x4f, 0x2f, 0x8f, 0xf3, 0x3f, 0xaf, 0xf0, 0x9c, 0xbb, 0x46, 0xc1, 0x5d,
	0x1b, 0x2a, 0xe2, 0x9b, 0x93, 0xa1, 0xb1, 0x0d, 0xcc, 0xe1, 0x63, 0xae, 0x71, 0xe4, 0xca, 0xff,
	0xa5, 0x3e, 0xb7, 0xd4, 0xff, 0x52, 0xc0, 0xdc, 0xf7, 0x62, 0x8e, 0x67, 0x9c, 0xd0, 0x65, 0x13,
	0x80, 0xc3, 0x35, 0x08, 0x4a, 0x4b, 0xfd, 0x0e, 0xd4, 0x19, 0x60, 0x62, 0x75, 0xb1, 0x5a, 0xcf,
	0x21, 0xa8, 0xcf, 0x21, 0x9c, 0x51, 0x8a, 0x4e, 0x13, 0x0c, 0xdf, 0x1b, 0x79, 0x02, 0x5e, 0xc3,
	0x11, 0x02, 0xc3, 0x2c, 0x1c, 0x0e, 0x63, 0x42, 0x39, 0xa6, 0x86, 0x23, 0x25, 0xbb, 0x07, 0x2b,
	0x99, 0x70, 0x24, 0x3f, 0xef, 0x82, 0xc1, 0x8a, 0x29, 0xb6, 0x14, 0x0e, 0xe0, 0xac, 0xc6, 0x84,
	0x9a, 0x5d, 0x41, 0x43, 0x8a, 0x7d, 0x39, 0xc3, 0x09, 0xc1, 0xfe, 0x49, 0x87, 0x8d, 0xe4, 0xac,
	0x2c, 0xdc, 0x69, 0x9a, 0xd6, 0x40, 0x4e, 0x6b, 0x92, 0xfa, 0x97, 0x66, 0x37, 0xb5, 0x7c, 0x76,
	0xd3, 0x72, 0x2c, 0xb3, 0x20, 0x99, 0xd5, 0x64, 0x62, 0xd2, 0xd1, 0x6d, 0x07, 0x96, 0x53, 0x4a,
	0x1c, 0x51, 0x1c, 0x2d, 0xd2, 0x93, 0x0b, 0x3b, 0xd0, 0x0b, 0x58, 0x4a, 0x35, 0xdd, 0xc0, 0x95,
	0x35, 0x72, 0xd5, 0x09, 0x39, 0x7b, 0xf4, 0x35, 0x34, 0x44, 0x97, 0x17, 0x0e, 0x54, 0xaf, 0xdd,
	0x9e, 0x35, 0x67, 0x3c, 0x16, 0x22, 0xbb, 0xba, 0x76, 0x3d, 0x8f, 0x53, 0xe3, 0xcc, 0x90, 0x53,
	0x5f, 0x78, 0xc8, 0x49, 0x46, 0x54, 0xb8, 0x76, 0x44, 0x4d, 0x39, 0xd5, 0x28, 0xe7, 0xd4, 0x52,
	0x8e, 0x53, 0x6f, 0x61, 0x73, 0x0e, 0x0f, 0x24, 0xbf, 0x9e, 0x15, 0x1f, 0x0a, 0xc1, 0xb3, 0x66,
	0x99, 0xcf, 0xc5, 0x47, 0xa2, 0x9c, 0x7b, 0x6f, 0xa1, 0x25, 0x1f, 0xd9, 0x9d, 0x69, 0x97, 0xd1,
	0xa7, 0x13, 0xb8, 0x87, 0x69, 0xf5, 0xa6, 0xd3, 0xa1, 0xa0, 0x99, 0x32, 0xaf, 0xab, 0xaa, 0x85,
	0xae, 0x9a, 0xab, 0x42, 0x2d, 0x5f, 0x85, 0xf6, 0x57, 0xd0, 0xe4, 0xef, 0xc2, 0x42, 0xd7, 0xd8,
	0x0f, 0xe0, 0x56, 0xc1, 0x5a, 0xe6, 0x82, 0xc7, 0xc3, 0xde, 0x1c, 0x69, 0xce, 0x05, 0xbb, 0x07,
	0xb7, 0x44, 0xe7, 0x2b, 0x39, 0xfd, 0xb2, 0xf9, 0x55, 0x41, 0xd8, 0x16, 0xac, 0x15, 0x8f, 0x12,
	0x57, 0xdb, 0x21, 0xac, 0x16, 0xf0, 0x19, 0x87, 0x11, 0x45, 0x08, 0x74, 0xc6, 0x2b, 0x7e, 0x83,
	0xe1, 0xf0, 0x6f, 0x06, 0xf5, 0x10, 0x7b, 0x3e, 0x71, 0x65, 0xda, 0xa5, 0xc4, 0x8a, 0x71, 0x4c,
	0x02, 0xd7, 0x0b, 0xce, 0x79, 0x7e, 0x0c, 0x27, 0x11, 0xd9, 0x29, 0x67, 0x61, 0x4c, 0x79, 0x8d,
	0xaa, 0x0e, 0xff, 0xb6, 0x7f, 0x55, 0xa0, 0x22, 0x2f, 0x49, 0x61, 0x54, 0x32, 0x30, 0xa6, 0x9b,
	0xd4, 0xd9, 0x26, 0xc6, 0x52, 0x17, 0x53, 0x6c, 0x69, 0x33, 0x8e, 0x88, 0x33, 0xda, 0xbb, 0x98,
	0xe2, 0x6e, 0x40, 0xa3, 0xa9, 0xc3, 0x2d, 0xd6, 0x0f, 0xa1, 0x9e, 0xaa, 0x90, 0x09, 0xda, 0x05,
	0x99, 0xca, 0x34, 0xb1, 0x4f, 0xf4, 0x00, 0x8c, 0x77, 0xd8, 0x9f, 0x10, 0x39, 0x19, 0xdc, 0x2e,
	0xf2, 0x5d, 0xc6, 0xef, 0x08, 0xab, 0x67, 0xea, 0x13, 0xc5, 0x6e, 0x83, 0xb9, 0x47, 0xa8, 0xd4,
	0x4b, 0x04, 0xb2, 0x43, 0x93, 0x52, 0xe0, 0xc4, 0x3f, 0x0a, 0x54, 0x44, 0x2b, 0xbd, 0xd4, 0xe3,
	0x11, 0xe8, 0x99, 0xf7, 0x9f, 0x7f, 0x8b, 0x70, 0xdd, 0xe4, 0x81, 0xe3, 0xdf, 0x73, 0x3a, 0xfa,
	0x1a, 0x54, 0xce, 0x22, 0xe2, 0x7a, 0xe2, 0x49, 0x53, 0x1d, 0x29, 0xb1, 0x1f, 0x59, 0x3f, 0x3c,
	0x0f, 0x07, 0x93, 0xc8, 0x97, 0xb3, 0x5d, 0x95, 0xc9, 0x27, 0x91, 0x5f, 0xf8, 0xad, 0xac, 0xbe,
	0x4f, 0x3b, 0x7d, 0x0a, 0x20, 0x3b, 0x24, 0xdb, 0x5a, 0x7b, 0x8f, 0x7e, 0x6a, 0x07, 0xb0, 0x2a,
	0x06, 0x3b, 0x39, 0x51, 0xc8, 0xa4, 0x25, 0xd1, 0x2b, 0x25, 0xd1, 0xab, 0x65, 0xd1, 0xe7, 0xba,
	0xe1, 0xfc, 0x28, 0xed, 0x11, 0xac, 0x0a, 0x76, 0xe7, 0xef, 0x9b, 0x0d, 0x39, 0xca, 0xdc, 0x21,
	0xe7, 0x43, 0x46, 0x45, 0x9b, 0x13, 0x22, 0x7f, 0x57, 0x71, 0x6a, 0xfd, 0x0e, 0x10, 0x7b, 0xfe,
	0x84, 0x51, 0x9c, 0xc9, 0x00, 0x8f, 0x56, 0xc9, 0x44, 0x9b, 0x34, 0x72, 0xb5, 0xb4, 0x91, 0x8b,
	0x73, 0xb5, 0xf4, 0xdc, 0xe7, 0xb0, 0x9a, 0x3b, 0x57, 0x3e, 0x20, 0xf7, 0xa0, 0x2a, 0x02, 0x4a,
	0x9e, 0xd1, 0x6c, 0xac, 0xc9, 0x92, 0xfd, 0xb3, 0x0a, 0xd5, 0x43, 0x3c, 0x1d, 0x91, 0xe0, 0x3d,
	0xa7, 0x5b, 0x13, 0xb4, 0x88, 0x0c, 0x25, 0x1e, 0xec, 0x93, 0x71, 0x11, 0x8f, 0xc2, 0x49, 0x90,
	0xd4, 0xb6, 0x94, 0xd0, 0x37, 0xb0, 0x34, 0x16, 0x37, 0x0c, 0x18, 0x20, 0x0b, 0x34, 0xdf, 0x86,
	0xb4, 0xdf, 0xc5, 0x94, 0xa0, 0xdb, 0x50, 0x1d, 0x63, 0xcf, 0x1d, 0x9c, 0x4e, 0xe5, 0x9f, 0x67,
	0x85, 0x89, 0x3b, 0xd3, 0x8f, 0x21, 0xf2, 0xe6, 0x6c, 0xeb, 0xe9, 0x94, 0x13, 0x59, 0x4b, 0x97,
	0x77, 0xa6, 0xf6, 0x6b, 0x58, 0xd9, 0x63, 0x4f, 0x32, 0x77, 0x22, 0x01, 0x2a, 0x97, 0x8d, 0x42,
	0x81, 0xb3, 0x03, 0x93, 0x18, 0xd3, 0x5c, 0xd5, 0xa5, 0xa6, 0xe7, 0xda, 0xbf, 0x2b, 0xd0, 0x14,
	0xf4, 0x2f, 0x1c, 0x7a, 0xc5, 0xa3, 0x91, 0x64, 0x58, 0x2d, 0xcb, 0xb0, 0x76, 0x65, 0x86, 0xf5,
	0x0f, 0xce, 0xb0, 0x91, 0xcd, 0xb0, 0xfd, 0x48, 0x30, 0x4b, 0xfa, 0x1c, 0x2f, 0xf2, 0xd2, 0x7d,
	0x0b, 0xcd, 0xfc, 0x16, 0xc9, 0xc6, 0x2f, 0x59, 0x27, 0x12, 0x3a, 0x49, 0xc7, 0x06, 0xa3, 0x63,
	0x92, 0x8e, 0x74, 0xf1, 0xfe, 0x03, 0xd0, 0x19, 0xd7, 0x51, 0x0d, 0xf4, 0x93, 0xa3, 0xae, 0x63,
	0xde, 0x40, 0x26, 0x2c, 0x1d, 0x77, 0xfb, 0x9d, 0xfe, 0xf1, 0xa0, 0xb3, 0x7b, 0xd0, 0xeb, 0x9b,
	0x0a, 0xaa, 0x83, 0x21, 0x3e, 0xd5, 0xfb, 0xcf, 0xc0, 0x2c, 0xce, 0x26, 0x6c, 0x6b, 0xff, 0x75,
	0xbf, 0x6b, 0xde, 0x40, 0x55, 0xd0, 0x8e, 0x0e, 0x8e, 0x4c, 0x85, 0xa9, 0x5e, 0x76, 0xf6, 0xf7,
	0x4d, 0x95, 0xed, 0xed, 0x1e, 0x74, 0x7a, 0xfb, 0xa6, 0x76, 0xff, 0x39, 0xac, 0x95, 0x4f, 0x42,
	0xa8, 0x01, 0xd5, 0xc3, 0x6e, 0x7f, 0xb7, 0xd7, 0xdf, 0x33, 0x6f, 0xb0, 0xbd, 0x47, 0xdd, 0xfe,
	0xb1, 0xa9, 0x20, 0x80, 0xca, 0xab, 0x4e, 0x6f, 0xbf, 0xbb, 0x6b, 0xaa, 0xa7, 0x15, 0x9e, 0xd5,
	0xc7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x7c, 0x59, 0x4a, 0x6e, 0x15, 0x00, 0x00,
}
